export const cpClientsPageCopy = {
  uz: {
    headTitle: 'Mijozlar',
    eyebrow: 'Client workspace',
    title: 'Mijozlar bazasi tez va aniq boshqariladi',
    subtitle: "Server-side qidiruv, tezkor topup va barcha mijoz oqimlari bitta ish maydonida.",
    updatedAt: 'Yangilangan',
    searchPlaceholder: 'Login, account, telefon yoki ism boyicha qidiring...',
    statusAll: 'Barcha statuslar',
    refresh: 'Yangilash',
    refreshing: 'Yuklanmoqda...',
    addClient: 'Yangi mijoz',
    clearSearch: 'Tozalash',
    tableTitle: "Mijozlar royxati",
    tableSubtitle: "Qidiruv butun baza boyicha ishlaydi, jadval esa faqat korinadigan qatorlarni render qiladi.",
    totalClients: 'Jami topilgan',
    currentPage: 'Joriy sahifa',
    selectedClients: 'Tanlangan',
    pageBalance: 'Sahifa balansi',
    pageBonus: 'Sahifa bonusi',
    totalLabel: 'Jami',
    pageLabel: 'Sahifa',
    resultRange: '{from}-{to} / {total}',
    noRows: 'Mijoz topilmadi.',
    noPhone: 'Telefon yoq',
    noAccount: 'Account yoq',
    noStatus: 'Nomalum',
    prev: 'Oldingi',
    next: 'Keyingi',
    clearSelection: 'Tanlovni tozalash',
    bulkTopup: 'Bulk topup',
    table: {
      client: 'Mijoz',
      tier: 'Rank',
      balance: 'Balans',
      bonus: 'Bonus',
      status: 'Holat',
      actions: 'Amallar',
      created: 'Yaratilgan',
      phone: 'Telefon',
      account: 'Account',
    },
    actions: {
      topup: 'Topup',
      history: 'History',
      ranks: 'Ranklar',
      more: 'Koproq',
      sessions: 'Sessiyalar',
      package: 'Paket biriktirish',
      packages: 'Paketlar',
      subscribe: 'Obuna ochish',
      subscriptions: 'Obunalar',
      returns: 'Qaytarish',
      transfer: 'Otkazish',
    },
    statuses: {
      active: 'Aktiv',
      blocked: 'Bloklangan',
      inactive: 'Faol emas',
      expired: 'Muddati tugagan',
    },
    ranks: {
      title: 'Mijoz ranklari',
      lifetime: 'Lifetime topup',
      nextTarget: 'Keyingi rankgacha',
      completed: 'Tugallangan',
      pending: 'Kutilmoqda',
      max: 'Maksimal rank',
      left: 'Qoldi: {value}',
      names: {
        rookie: 'Novobranets',
        squire: 'Orujenosets',
        knight: 'Ritsar',
        captain: 'Kapitan',
        baron: 'Барон',
        investor: 'Инвестор',
        legend: 'Legenda',
      },
    },
    bulk: {
      title: 'Bulk topup',
      subtitle: '{count} ta tanlangan mijoz',
      amount: 'Summa',
      bonus: 'Qoshimcha bonus',
      method: 'Tolov turi',
      cash: 'Naqd',
      card: 'Карта',
      apply: 'Qollash',
      cancel: 'Bekor qilish',
      loadingPromo: 'Promo tekshirilmoqda...',
      promoActive: 'Promo aktiv',
      promoBonus: 'Avtomatik bonus: +{value}',
      failed: 'Bulk topup amalga oshmadi.',
    },
  },
  ru: {
    headTitle: 'Клиенты',
    eyebrow: 'Client workspace',
    title: 'База клиентов управляется быстрее и понятнее',
    subtitle: 'Server-side поиск, быстрый топап и все клиентские потоки в одном рабочем месте.',
    updatedAt: 'Обновлено',
    searchPlaceholder: 'Поиск по логину, account, телефону или имени...',
    statusAll: 'Все статусы',
    refresh: 'Обновить',
    refreshing: 'Загрузка...',
    addClient: 'Новый клиент',
    clearSearch: 'Очистить',
    tableTitle: 'Список клиентов',
    tableSubtitle: 'Поиск работает по всей базе, а таблица рендерит только видимые строки.',
    totalClients: 'Всего найдено',
    currentPage: 'Текущая страница',
    selectedClients: 'Выбрано',
    pageBalance: 'Баланс страницы',
    pageBonus: 'Бонус страницы',
    totalLabel: 'Всего',
    pageLabel: 'Страница',
    resultRange: '{from}-{to} / {total}',
    noRows: 'Клиенты не найдены.',
    noPhone: 'Нет телефона',
    noAccount: 'Нет account',
    noStatus: 'Неизвестно',
    prev: 'Назад',
    next: 'Далее',
    clearSelection: 'Сбросить выбор',
    bulkTopup: 'Массовый топап',
    table: {
      client: 'Клиент',
      tier: 'Ранг',
      balance: 'Баланс',
      bonus: 'Бонус',
      status: 'Статус',
      actions: 'Действия',
      created: 'Создан',
      phone: 'Телефон',
      account: 'Account',
    },
    actions: {
      topup: 'Пополнить',
      history: 'История',
      ranks: 'Ранги',
      more: 'Еще',
      sessions: 'Сессии',
      package: 'Добавить пакет',
      packages: 'Пакеты',
      subscribe: 'Открыть подписку',
      subscriptions: 'Подписки',
      returns: 'Возврат',
      transfer: 'Перевод',
    },
    statuses: {
      active: 'Активен',
      blocked: 'Заблокирован',
      inactive: 'Неактивен',
      expired: 'Истек',
    },
    ranks: {
      title: 'Ранги клиента',
      lifetime: 'Lifetime topup',
      nextTarget: 'До следующего ранга',
      completed: 'Завершено',
      pending: 'Ожидает',
      max: 'Максимальный ранг',
      left: 'Осталось: {value}',
      names: {
        rookie: 'Новобранец',
        squire: 'Оруженосец',
        knight: 'Рыцарь',
        captain: 'Капитан',
        baron: 'Baron',
        investor: 'Investor',
        legend: 'Легенда',
      },
    },
    bulk: {
      title: 'Массовый топап',
      subtitle: 'Выбрано клиентов: {count}',
      amount: 'Сумма',
      bonus: 'Доп. бонус',
      method: 'Способ оплаты',
      cash: 'Наличные',
      card: 'Karta',
      apply: 'Применить',
      cancel: 'Отмена',
      loadingPromo: 'Проверяем акцию...',
      promoActive: 'Акция активна',
      promoBonus: 'Автобонус: +{value}',
      failed: 'Не удалось выполнить массовый топап.',
    },
  },
  en: {
    headTitle: 'Clients',
    eyebrow: 'Client workspace',
    title: 'Client data is faster and easier to operate',
    subtitle: 'Server-side search, quick topup, and all client flows in one workspace.',
    updatedAt: 'Updated',
    searchPlaceholder: 'Search by login, account, phone, or name...',
    statusAll: 'All statuses',
    refresh: 'Refresh',
    refreshing: 'Loading...',
    addClient: 'New client',
    clearSearch: 'Clear',
    tableTitle: 'Clients list',
    tableSubtitle: 'Search runs across the full database while the grid renders only visible rows.',
    totalClients: 'Total found',
    currentPage: 'Current page',
    selectedClients: 'Selected',
    pageBalance: 'Page balance',
    pageBonus: 'Page bonus',
    totalLabel: 'Total',
    pageLabel: 'Page',
    resultRange: '{from}-{to} / {total}',
    noRows: 'No clients found.',
    noPhone: 'No phone',
    noAccount: 'No account',
    noStatus: 'Unknown',
    prev: 'Previous',
    next: 'Next',
    clearSelection: 'Clear selection',
    bulkTopup: 'Bulk topup',
    table: {
      client: 'Client',
      tier: 'Rank',
      balance: 'Balance',
      bonus: 'Bonus',
      status: 'Status',
      actions: 'Actions',
      created: 'Created',
      phone: 'Phone',
      account: 'Account',
    },
    actions: {
      topup: 'Topup',
      history: 'History',
      ranks: 'Ranks',
      more: 'More',
      sessions: 'Sessions',
      package: 'Attach package',
      packages: 'Packages',
      subscribe: 'Start subscription',
      subscriptions: 'Subscriptions',
      returns: 'Return',
      transfer: 'Transfer',
    },
    statuses: {
      active: 'Active',
      blocked: 'Blocked',
      inactive: 'Inactive',
      expired: 'Expired',
    },
    ranks: {
      title: 'Client ranks',
      lifetime: 'Lifetime topup',
      nextTarget: 'To next rank',
      completed: 'Completed',
      pending: 'Pending',
      max: 'Max rank',
      left: 'Left: {value}',
      names: {
        rookie: 'Rookie',
        squire: 'Squire',
        knight: 'Knight',
        captain: 'Captain',
        baron: 'Baron',
        investor: 'Investor',
        legend: 'Legend',
      },
    },
    bulk: {
      title: 'Bulk topup',
      subtitle: '{count} selected clients',
      amount: 'Amount',
      bonus: 'Extra bonus',
      method: 'Payment method',
      cash: 'Cash',
      card: 'Card',
      apply: 'Apply',
      cancel: 'Cancel',
      loadingPromo: 'Checking promotion...',
      promoActive: 'Promotion active',
      promoBonus: 'Auto bonus: +{value}',
      failed: 'Bulk topup failed.',
    },
  },
}
