export const cpNativePageCopy = {
  dashboard: {
    uz: {
      headTitle: 'Dashboard',
      eyebrow: 'Control overview',
      title: 'Dashboard',
      subtitle: "Smena, zal holati, bookinglar va muhim signal bir ekranda.",
      updatedAt: 'Oxirgi yangilanish',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      shift: 'Smena',
      shiftOpen: 'Ochiq',
      shiftClosed: 'Yopiq',
      shiftNeedOpen: 'Yangi smena ochish kerak',
      live: 'Live',
      idle: 'Idle',
      cashflow: 'Kassa oqimi',
      activeSessions: 'Aktiv sessiyalar',
      hallOccupancy: 'Zal bandligi',
      averageMinutes: "O'rtacha {value} min",
      longestMinutes: 'Eng uzun {value} min',
      liveSessionsTitle: 'Jonli sessiyalar',
      liveSessionsSubtitle: "Hozir aktiv bo'lgan mijozlar va tezkor tugatish",
      hallView: "Zal ko'rinishi",
      pc: 'PC',
      client: 'Mijoz',
      startedAt: 'Boshlangan',
      duration: 'Davomiylik',
      stop: 'Tugatish',
      noActiveSessions: 'Aktiv sessiya topilmadi.',
      bookingQueueTitle: 'Booking navbati',
      bookingQueueSubtitle: "Kelish vaqti yaqin yoki o'tib ketgan bronlar",
      all: 'Hammasi',
      cancel: 'Bekor qilish',
      noActiveBookings: "Aktiv booking yo'q.",
      signalsTitle: 'Muhim signal',
      signalsSubtitle: 'Oxirgi xatolar va kutayotgan commandlar',
      failedCommand: 'Failed command',
      pendingCommand: 'Pending command',
      offlinePc: 'Offline PC',
      noImportantLogs: "Muhim log yo'q.",
      noNote: "Izoh yo'q",
      operatorFlowTitle: 'Operator oqimi',
      operatorFlowSubtitle: 'Bugungi smena kesimi',
      expectedCash: 'Expected cash',
      expenses: 'Xarajat',
      bonus: 'Bonus',
      operations: 'Operatsiya',
      confirmTitle: 'Tasdiqlash',
      confirmYes: 'Ha',
      confirmNo: "Yo'q",
      stopSessionConfirm: 'Sessiyani tugatilsinmi?',
      cancelBookingConfirm: 'Booking bekor qilinsinmi?',
    },
    ru: {
      headTitle: 'Дашборд',
      eyebrow: 'Обзор управления',
      title: 'Дашборд',
      subtitle: 'Смена, зал, брони и важные сигналы собраны на одном экране.',
      updatedAt: 'Последнее обновление',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      shift: 'Смена',
      shiftOpen: 'Открыта',
      shiftClosed: 'Закрыта',
      shiftNeedOpen: 'Нужно открыть новую смену',
      live: 'Live',
      idle: 'Idle',
      cashflow: 'Денежный поток',
      activeSessions: 'Активные сессии',
      hallOccupancy: 'Загрузка зала',
      averageMinutes: 'Среднее {value} мин',
      longestMinutes: 'Максимум {value} мин',
      liveSessionsTitle: 'Живые сессии',
      liveSessionsSubtitle: 'Активные клиенты и быстрое завершение сессии',
      hallView: 'Вид зала',
      pc: 'ПК',
      client: 'Клиент',
      startedAt: 'Старт',
      duration: 'Длительность',
      stop: 'Завершить',
      noActiveSessions: 'Активные сессии не найдены.',
      bookingQueueTitle: 'Очередь бронирований',
      bookingQueueSubtitle: 'Ближайшие и просроченные брони',
      all: 'Все',
      cancel: 'Отменить',
      noActiveBookings: 'Активных броней нет.',
      signalsTitle: 'Важные сигналы',
      signalsSubtitle: 'Последние ошибки и ожидающие команды',
      failedCommand: 'Ошибочные команды',
      pendingCommand: 'Ожидающие команды',
      offlinePc: 'Офлайн ПК',
      noImportantLogs: 'Важных логов нет.',
      noNote: 'Нет комментария',
      operatorFlowTitle: 'Поток оператора',
      operatorFlowSubtitle: 'Срез по текущей смене',
      expectedCash: 'Ожидаемая наличность',
      expenses: 'Расходы',
      bonus: 'Бонус',
      operations: 'Операции',
      confirmTitle: 'Подтверждение',
      confirmYes: 'Да',
      confirmNo: 'Нет',
      stopSessionConfirm: 'Завершить эту сессию?',
      cancelBookingConfirm: 'Отменить это бронирование?',
    },
    en: {
      headTitle: 'Dashboard',
      eyebrow: 'Control overview',
      title: 'Dashboard',
      subtitle: 'Shift, hall state, bookings, and important signals on one screen.',
      updatedAt: 'Last update',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      shift: 'Shift',
      shiftOpen: 'Open',
      shiftClosed: 'Closed',
      shiftNeedOpen: 'A new shift needs to be opened',
      live: 'Live',
      idle: 'Idle',
      cashflow: 'Cashflow',
      activeSessions: 'Active sessions',
      hallOccupancy: 'Hall occupancy',
      averageMinutes: 'Average {value} min',
      longestMinutes: 'Longest {value} min',
      liveSessionsTitle: 'Live sessions',
      liveSessionsSubtitle: 'Active customers and quick session stop',
      hallView: 'Hall view',
      pc: 'PC',
      client: 'Client',
      startedAt: 'Started',
      duration: 'Duration',
      stop: 'Stop',
      noActiveSessions: 'No active sessions found.',
      bookingQueueTitle: 'Booking queue',
      bookingQueueSubtitle: 'Upcoming and overdue bookings',
      all: 'All',
      cancel: 'Cancel',
      noActiveBookings: 'No active bookings.',
      signalsTitle: 'Important signals',
      signalsSubtitle: 'Recent failures and pending commands',
      failedCommand: 'Failed commands',
      pendingCommand: 'Pending commands',
      offlinePc: 'Offline PCs',
      noImportantLogs: 'No important logs.',
      noNote: 'No note',
      operatorFlowTitle: 'Operator flow',
      operatorFlowSubtitle: "Today's shift summary",
      expectedCash: 'Expected cash',
      expenses: 'Expenses',
      bonus: 'Bonus',
      operations: 'Operations',
      confirmTitle: 'Confirm',
      confirmYes: 'Yes',
      confirmNo: 'No',
      stopSessionConfirm: 'Stop this session?',
      cancelBookingConfirm: 'Cancel this booking?',
    },
  },
  pcs: {
    uz: {
      headTitle: 'Kompyuterlar',
      eyebrow: 'Hall control',
      title: 'Kompyuterlar',
      subtitle: "Filtrlash, status bo'yicha ko'rish va eng kerakli commandlar bitta joyda.",
      searchPlaceholder: "PC kodi yoki IP bo'yicha qidiring...",
      allZones: 'Barcha zonalar',
      allStatuses: 'Barcha holatlar',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      total: 'Jami',
      reserved: 'Bron',
      visible: "Ko'rinayotgan",
      noZone: 'Zonasiz',
      noIp: "IP yo'q",
      noClient: "Mijoz yo'q",
      noTariff: "Tarif yo'q",
      noLastSeen: "Aloqa yo'q",
      client: 'Mijoz',
      tariff: 'Tarif',
      balance: 'Balans',
      lastSeen: 'Oxirgi aloqa',
      layout: 'Layout',
      lock: 'Lock',
      reboot: 'Reboot',
      shutdown: 'Shutdown',
      confirmTitle: 'Tasdiqlash',
      confirmYes: 'Ha',
      confirmNo: "Yo'q",
      sendCommandConfirm: '{pc} uchun {type} yuborilsinmi?',
      commandSent: '{type} yuborildi',
      statuses: {
        online: 'Online',
        busy: 'Busy',
        reserved: 'Reserved',
        offline: 'Offline',
        locked: 'Locked',
      },
    },
    ru: {
      headTitle: 'Компьютеры',
      eyebrow: 'Управление залом',
      title: 'Компьютеры',
      subtitle: 'Фильтры, статусы и самые нужные команды собраны в одном месте.',
      searchPlaceholder: 'Ищите по коду ПК или IP...',
      allZones: 'Все зоны',
      allStatuses: 'Все статусы',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      total: 'Всего',
      reserved: 'Бронь',
      visible: 'Показано',
      noZone: 'Без зоны',
      noIp: 'Нет IP',
      noClient: 'Нет клиента',
      noTariff: 'Нет тарифа',
      noLastSeen: 'Нет связи',
      client: 'Клиент',
      tariff: 'Тариф',
      balance: 'Баланс',
      lastSeen: 'Последний контакт',
      layout: 'Схема',
      lock: 'Блок',
      reboot: 'Перезагрузка',
      shutdown: 'Выключить',
      confirmTitle: 'Подтверждение',
      confirmYes: 'Да',
      confirmNo: 'Нет',
      sendCommandConfirm: 'Отправить {type} для {pc}?',
      commandSent: 'Команда {type} отправлена',
      statuses: {
        online: 'Online',
        busy: 'Busy',
        reserved: 'Reserved',
        offline: 'Offline',
        locked: 'Locked',
      },
    },
    en: {
      headTitle: 'PCs',
      eyebrow: 'Hall control',
      title: 'PCs',
      subtitle: 'Filters, statuses, and the most useful commands in one place.',
      searchPlaceholder: 'Search by PC code or IP...',
      allZones: 'All zones',
      allStatuses: 'All statuses',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      total: 'Total',
      reserved: 'Reserved',
      visible: 'Visible',
      noZone: 'No zone',
      noIp: 'No IP',
      noClient: 'No client',
      noTariff: 'No tariff',
      noLastSeen: 'No contact',
      client: 'Client',
      tariff: 'Tariff',
      balance: 'Balance',
      lastSeen: 'Last seen',
      layout: 'Layout',
      lock: 'Lock',
      reboot: 'Reboot',
      shutdown: 'Shutdown',
      confirmTitle: 'Confirm',
      confirmYes: 'Yes',
      confirmNo: 'No',
      sendCommandConfirm: 'Send {type} to {pc}?',
      commandSent: '{type} sent',
      statuses: {
        online: 'Online',
        busy: 'Busy',
        reserved: 'Reserved',
        offline: 'Offline',
        locked: 'Locked',
      },
    },
  },
  layout: {
    uz: {
      headTitle: 'Layout',
      eyebrow: 'Operatsion xarita',
      title: 'Zal sxemasi',
      subtitle: "Joylashuv, status va aktiv sessiyalarni bitta interaktiv map orqali boshqaring.",
      updatedAt: 'Oxirgi yangilanish',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      autoRefresh: 'Auto refresh',
      totalPcs: 'Jami PC',
      activeNow: 'Aktiv hozir',
      reservedNow: 'Bron hozir',
      freeNow: "Bo'sh joy",
      legendTitle: 'Zal nazorati',
      legendSubtitle: 'Holat, signal va bo‘sh qurilmalarni bir joyda ko‘ring.',
      detailsTitle: 'Tanlangan katak',
      detailsSubtitle: 'Katak va PC bo‘yicha tezkor boshqaruv.',
      hallTitle: 'Interaktiv zal',
      hallSubtitle: 'Drag-and-drop bilan joylashuvni yangilang, hover bilan sessiyani ko‘ring.',
      freeTrayTitle: "Bo'sh PC'lar",
      freeTrayHint: 'Bo‘sh qurilmani katakka sudrab joylashtiring.',
      trayEmpty: 'Hozir bo‘sh PC yo‘q.',
      signalsTitle: 'Diqqat markazi',
      signalsSubtitle: 'Aloqa uzilgan yoki bloklangan qurilmalar.',
      noSelection: 'Katak yoki PC tanlang, tafsilotlar shu yerda chiqadi.',
      selectedCell: 'Katak',
      selectedPc: 'PC',
      selectedStatus: 'Holat',
      sessionClient: 'Sessiya mijozi',
      tariff: 'Tarif',
      balance: 'Balans',
      lastSeen: 'Oxirgi aloqa',
      network: 'Tarmoq',
      hardware: 'Qurilma',
      notes: 'Izoh',
      noNotes: "Izoh yo'q",
      noIp: "IP yo'q",
      noClient: "Mijoz yo'q",
      noTariff: "Tarif yo'q",
      noHardware: "Ma'lumot yo'q",
      cpu: 'CPU',
      ram: 'RAM',
      gpu: 'GPU',
      disks: 'Disklar',
      detach: 'Ajratish',
      stopSession: 'Sessiyani tugatish',
      reboot: 'Qayta yuklash',
      shutdown: "O'chirish",
      clientInfo: 'Mijoz maʼlumoti',
      activeSession: 'Aktiv sessiya',
      sessionUntil: '{time} gacha',
      reservedUntil: '{time} gacha bron',
      confirmTitle: 'Tasdiqlash',
      confirmYes: 'Ha',
      confirmNo: "Yo'q",
      detachConfirm: '{pc} katakdan ajratilsinmi?',
      stopConfirm: '{pc} dagi sessiya tugatilsinmi?',
      rebootConfirm: '{pc} qayta yuklansinmi?',
      shutdownConfirm: '{pc} o‘chirilsinmi?',
      detached: 'PC ajratildi.',
      sessionStopped: 'Sessiya tugatildi.',
      commandSent: '{type} yuborildi.',
      loadError: 'Layout maʼlumotlarini yuklab bo‘lmadi.',
      saveError: 'Layout yangilanmadi.',
      clientModalTitle: 'Sessiya mijozi',
      login: 'Login',
      phone: 'Telefon',
      accountId: 'Account ID',
      startedAt: 'Boshlangan',
      statuses: {
        online: 'Online',
        busy: 'Band',
        reserved: 'Bron',
        offline: "O'chirilgan",
        locked: 'Bloklangan',
        maintenance: 'Xizmat',
        empty: "Bo'sh",
      },
      alerts: {
        offline: "Aloqa yo'q",
        locked: 'Bloklangan',
        maintenance: 'Xizmat rejimi',
      },
    },
    ru: {
      headTitle: 'Схема',
      eyebrow: 'Операционная карта',
      title: 'Схема зала',
      subtitle: 'Управляйте расположением, статусами и активными сессиями через одну интерактивную карту.',
      updatedAt: 'Последнее обновление',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      autoRefresh: 'Автообновление',
      totalPcs: 'Всего ПК',
      activeNow: 'Активны сейчас',
      reservedNow: 'Броней сейчас',
      freeNow: 'Свободно',
      legendTitle: 'Контроль зала',
      legendSubtitle: 'Сводка по статусам, сигналам и свободным устройствам.',
      detailsTitle: 'Выбранная ячейка',
      detailsSubtitle: 'Быстрое управление ячейкой и ПК.',
      hallTitle: 'Интерактивная карта',
      hallSubtitle: 'Перетаскивайте ПК по сетке и просматривайте активные сессии по наведению.',
      freeTrayTitle: 'Свободные ПК',
      freeTrayHint: 'Перетащите свободный ПК в нужную ячейку.',
      trayEmpty: 'Сейчас нет свободных ПК.',
      signalsTitle: 'Требует внимания',
      signalsSubtitle: 'Устройства без связи или в блокировке.',
      noSelection: 'Выберите ячейку или ПК, и подробности появятся здесь.',
      selectedCell: 'Ячейка',
      selectedPc: 'ПК',
      selectedStatus: 'Статус',
      sessionClient: 'Клиент сессии',
      tariff: 'Тариф',
      balance: 'Баланс',
      lastSeen: 'Последний контакт',
      network: 'Сеть',
      hardware: 'Оборудование',
      notes: 'Заметка',
      noNotes: 'Нет заметки',
      noIp: 'Нет IP',
      noClient: 'Нет клиента',
      noTariff: 'Нет тарифа',
      noHardware: 'Нет данных',
      cpu: 'CPU',
      ram: 'RAM',
      gpu: 'GPU',
      disks: 'Диски',
      detach: 'Отвязать',
      stopSession: 'Завершить сессию',
      reboot: 'Перезагрузить',
      shutdown: 'Выключить',
      clientInfo: 'Данные клиента',
      activeSession: 'Активная сессия',
      sessionUntil: 'До {time}',
      reservedUntil: 'Бронь до {time}',
      confirmTitle: 'Подтверждение',
      confirmYes: 'Да',
      confirmNo: 'Нет',
      detachConfirm: 'Отвязать {pc} от ячейки?',
      stopConfirm: 'Завершить сессию на {pc}?',
      rebootConfirm: 'Перезагрузить {pc}?',
      shutdownConfirm: 'Выключить {pc}?',
      detached: 'ПК отвязан.',
      sessionStopped: 'Сессия завершена.',
      commandSent: 'Команда {type} отправлена.',
      loadError: 'Не удалось загрузить данные схемы.',
      saveError: 'Не удалось обновить схему.',
      clientModalTitle: 'Клиент сессии',
      login: 'Логин',
      phone: 'Телефон',
      accountId: 'Account ID',
      startedAt: 'Начало',
      statuses: {
        online: 'Online',
        busy: 'Занят',
        reserved: 'Бронь',
        offline: 'Выключен',
        locked: 'Заблокирован',
        maintenance: 'Сервис',
        empty: 'Свободно',
      },
      alerts: {
        offline: 'Нет связи',
        locked: 'Заблокирован',
        maintenance: 'Сервисный режим',
      },
    },
    en: {
      headTitle: 'Layout',
      eyebrow: 'Operations map',
      title: 'Hall layout',
      subtitle: 'Manage placement, statuses, and active sessions through one interactive map.',
      updatedAt: 'Last update',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      autoRefresh: 'Auto refresh',
      totalPcs: 'Total PCs',
      activeNow: 'Active now',
      reservedNow: 'Reserved now',
      freeNow: 'Free now',
      legendTitle: 'Hall control',
      legendSubtitle: 'See statuses, alerts, and free devices in one place.',
      detailsTitle: 'Selected cell',
      detailsSubtitle: 'Quick cell and PC controls.',
      hallTitle: 'Interactive map',
      hallSubtitle: 'Use drag and drop to update placement and hover to inspect active sessions.',
      freeTrayTitle: 'Free PCs',
      freeTrayHint: 'Drag a free device into any cell.',
      trayEmpty: 'No free PCs right now.',
      signalsTitle: 'Needs attention',
      signalsSubtitle: 'Devices with no contact or locked state.',
      noSelection: 'Select a cell or PC to see details here.',
      selectedCell: 'Cell',
      selectedPc: 'PC',
      selectedStatus: 'Status',
      sessionClient: 'Session client',
      tariff: 'Tariff',
      balance: 'Balance',
      lastSeen: 'Last seen',
      network: 'Network',
      hardware: 'Hardware',
      notes: 'Note',
      noNotes: 'No note',
      noIp: 'No IP',
      noClient: 'No client',
      noTariff: 'No tariff',
      noHardware: 'No data',
      cpu: 'CPU',
      ram: 'RAM',
      gpu: 'GPU',
      disks: 'Disks',
      detach: 'Detach',
      stopSession: 'Stop session',
      reboot: 'Reboot',
      shutdown: 'Shutdown',
      clientInfo: 'Client details',
      activeSession: 'Active session',
      sessionUntil: 'Until {time}',
      reservedUntil: 'Reserved until {time}',
      confirmTitle: 'Confirm',
      confirmYes: 'Yes',
      confirmNo: 'No',
      detachConfirm: 'Detach {pc} from this cell?',
      stopConfirm: 'Stop the session on {pc}?',
      rebootConfirm: 'Reboot {pc}?',
      shutdownConfirm: 'Shut down {pc}?',
      detached: 'PC detached.',
      sessionStopped: 'Session stopped.',
      commandSent: '{type} command sent.',
      loadError: 'Could not load layout data.',
      saveError: 'Could not update the layout.',
      clientModalTitle: 'Session client',
      login: 'Login',
      phone: 'Phone',
      accountId: 'Account ID',
      startedAt: 'Started',
      statuses: {
        online: 'Online',
        busy: 'Busy',
        reserved: 'Reserved',
        offline: 'Offline',
        locked: 'Locked',
        maintenance: 'Maintenance',
        empty: 'Empty',
      },
      alerts: {
        offline: 'No contact',
        locked: 'Locked',
        maintenance: 'Maintenance',
      },
    },
  },
  bookings: {
    uz: {
      headTitle: 'Bookinglar',
      eyebrow: 'Reservation flow',
      title: 'Bookinglar',
      subtitle: "Bron yaratish, navbatni ko'rish va kechikkan kelishlarni nazorat qilish bir sahifada.",
      updatedAt: 'Oxirgi yangilanish',
      total: 'Jami',
      statusAll: 'Barcha statuslar',
      searchPlaceholder: "PC yoki mijoz bo'yicha qidiruv...",
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      statsActive: 'Aktiv bronlar',
      statsUpcoming: 'ta yaqin kelish',
      statsOverdue: 'Kechikkanlar',
      statsToday: 'Bugun {value} ta booking',
      statsFiltered: 'Filter natijasi',
      newBookingTitle: 'Yangi booking',
      newBookingSubtitle: "PC va mijozni qidiring, keyin aniq kelish vaqtini belgilang.",
      pc: 'PC',
      pcPlaceholder: 'PC qidiring',
      client: 'Mijoz',
      clientPlaceholder: 'Mijoz qidiring',
      arrivalTime: 'Kelish vaqti',
      note: 'Izoh',
      notePlaceholder: 'Masalan: turnir uchun bron',
      arrival: 'Kelish',
      activeUntilArrival: "Kelgunga qadar active",
      create: 'Booking yaratish',
      creating: 'Saqlanmoqda...',
      queueTitle: 'Booking navbati',
      queueSubtitle: 'Eng yaqin kelishlar va kechikkan bronlar.',
      state: 'Holat',
      cancel: 'Bekor qilish',
      notFound: "Tanlangan filterlar bo'yicha booking topilmadi.",
      prev: 'Oldingi',
      next: 'Keyingi',
      created: 'Booking yaratildi.',
      createError: 'Booking yaratilmadi.',
      loadError: 'Bookinglarni yuklashda xato.',
      canceled: 'Booking bekor qilindi.',
      confirmTitle: 'Tasdiqlash',
      confirmYes: 'Ha',
      confirmNo: "Yo'q",
      cancelConfirm: 'Bu booking bekor qilinsinmi?',
      overdueMinutes: 'Kechikkan {value} min',
      leftMinutes: '{value} min qoldi',
      optionBalance: 'balans',
      optionBonus: 'bonus',
      statuses: {
        active: 'Aktiv',
        completed: 'Yakunlangan',
        canceled: 'Bekor qilingan',
        expired: 'Muddati tugagan',
      },
    },
    ru: {
      headTitle: 'Брони',
      eyebrow: 'Поток бронирований',
      title: 'Брони',
      subtitle: 'Создание, очередь и просроченные приходы контролируются на одной странице.',
      updatedAt: 'Последнее обновление',
      total: 'Всего',
      statusAll: 'Все статусы',
      searchPlaceholder: 'Поиск по ПК или клиенту...',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      statsActive: 'Активные брони',
      statsUpcoming: 'скоро прибывают',
      statsOverdue: 'Просроченные',
      statsToday: 'Сегодня {value} броней',
      statsFiltered: 'Результат фильтра',
      newBookingTitle: 'Новая бронь',
      newBookingSubtitle: 'Найдите ПК и клиента, затем укажите точное время прихода.',
      pc: 'ПК',
      pcPlaceholder: 'Найдите ПК',
      client: 'Клиент',
      clientPlaceholder: 'Найдите клиента',
      arrivalTime: 'Время прихода',
      note: 'Комментарий',
      notePlaceholder: 'Например: бронь для турнира',
      arrival: 'Приход',
      activeUntilArrival: 'Активно до прихода',
      create: 'Создать бронь',
      creating: 'Сохранение...',
      queueTitle: 'Очередь броней',
      queueSubtitle: 'Ближайшие и просроченные бронирования.',
      state: 'Состояние',
      cancel: 'Отменить',
      notFound: 'По текущему фильтру брони не найдены.',
      prev: 'Назад',
      next: 'Далее',
      created: 'Бронь создана.',
      createError: 'Не удалось создать бронь.',
      loadError: 'Не удалось загрузить брони.',
      canceled: 'Бронь отменена.',
      confirmTitle: 'Подтверждение',
      confirmYes: 'Да',
      confirmNo: 'Нет',
      cancelConfirm: 'Отменить это бронирование?',
      overdueMinutes: 'Просрочено на {value} мин',
      leftMinutes: 'Осталось {value} мин',
      optionBalance: 'баланс',
      optionBonus: 'бонус',
      statuses: {
        active: 'Активна',
        completed: 'Завершена',
        canceled: 'Отменена',
        expired: 'Истекла',
      },
    },
    en: {
      headTitle: 'Bookings',
      eyebrow: 'Reservation flow',
      title: 'Bookings',
      subtitle: 'Create bookings, monitor the queue, and track late arrivals on one page.',
      updatedAt: 'Last update',
      total: 'Total',
      statusAll: 'All statuses',
      searchPlaceholder: 'Search by PC or client...',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      statsActive: 'Active bookings',
      statsUpcoming: 'arriving soon',
      statsOverdue: 'Overdue',
      statsToday: '{value} bookings today',
      statsFiltered: 'Filtered result',
      newBookingTitle: 'New booking',
      newBookingSubtitle: 'Find a PC and a client, then set the exact arrival time.',
      pc: 'PC',
      pcPlaceholder: 'Search PC',
      client: 'Client',
      clientPlaceholder: 'Search client',
      arrivalTime: 'Arrival time',
      note: 'Note',
      notePlaceholder: 'For example: booking for tournament',
      arrival: 'Arrival',
      activeUntilArrival: 'Active until arrival',
      create: 'Create booking',
      creating: 'Saving...',
      queueTitle: 'Booking queue',
      queueSubtitle: 'Upcoming and overdue bookings.',
      state: 'State',
      cancel: 'Cancel',
      notFound: 'No bookings found for the selected filters.',
      prev: 'Previous',
      next: 'Next',
      created: 'Booking created.',
      createError: 'Booking could not be created.',
      loadError: 'Bookings could not be loaded.',
      canceled: 'Booking canceled.',
      confirmTitle: 'Confirm',
      confirmYes: 'Yes',
      confirmNo: 'No',
      cancelConfirm: 'Cancel this booking?',
      overdueMinutes: 'Overdue by {value} min',
      leftMinutes: '{value} min left',
      optionBalance: 'balance',
      optionBonus: 'bonus',
      statuses: {
        active: 'Active',
        completed: 'Completed',
        canceled: 'Canceled',
        expired: 'Expired',
      },
    },
  },
  returns: {
    uz: {
      headTitle: 'Qaytarishlar',
      eyebrow: 'Reversal control',
      title: 'Qaytarishlar',
      subtitle: "Bugungi va oldingi return operatsiyalarni bitta yengil ro'yxatda ko'ring.",
      updatedAt: 'Yangilanish',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      searchPlaceholder: 'Klient, operator yoki ID bo‘yicha qidiring...',
      allMethods: 'Barcha usullar',
      totalRows: 'Topildi',
      pageAmount: 'Sahifa summasi',
      cashReturns: 'Naqd return',
      count: 'Soni',
      noData: "Qaytarish topilmadi.",
      date: 'Sana',
      client: 'Klient',
      type: 'Turi',
      amount: 'Summa',
      method: 'To‘lov',
      operator: 'Operator',
      shift: 'Smena',
      reason: 'Sabab',
      page: 'Sahifa',
      prev: 'Oldingi',
      next: 'Keyingi',
      unknownClient: 'Noma’lum klient',
      unknownOperator: 'Noma’lum operator',
      noReason: 'Sabab kiritilmagan',
    },
    ru: {
      headTitle: 'Возвраты',
      eyebrow: 'Reversal control',
      title: 'Возвраты',
      subtitle: 'Текущие и прошлые возвраты собраны в одном легком списке.',
      updatedAt: 'Обновлено',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      searchPlaceholder: 'Поиск по клиенту, оператору или ID...',
      allMethods: 'Все способы',
      totalRows: 'Найдено',
      pageAmount: 'Сумма страницы',
      cashReturns: 'Наличные возвраты',
      count: 'Кол-во',
      noData: 'Возвраты не найдены.',
      date: 'Дата',
      client: 'Клиент',
      type: 'Тип',
      amount: 'Сумма',
      method: 'Оплата',
      operator: 'Оператор',
      shift: 'Смена',
      reason: 'Причина',
      page: 'Страница',
      prev: 'Назад',
      next: 'Далее',
      unknownClient: 'Неизвестный клиент',
      unknownOperator: 'Неизвестный оператор',
      noReason: 'Причина не указана',
    },
    en: {
      headTitle: 'Returns',
      eyebrow: 'Reversal control',
      title: 'Returns',
      subtitle: 'Current and past return operations are listed in one lightweight view.',
      updatedAt: 'Updated',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      searchPlaceholder: 'Search by client, operator, or ID...',
      allMethods: 'All methods',
      totalRows: 'Found',
      pageAmount: 'Page amount',
      cashReturns: 'Cash returns',
      count: 'Count',
      noData: 'No returns found.',
      date: 'Date',
      client: 'Client',
      type: 'Type',
      amount: 'Amount',
      method: 'Method',
      operator: 'Operator',
      shift: 'Shift',
      reason: 'Reason',
      page: 'Page',
      prev: 'Prev',
      next: 'Next',
      unknownClient: 'Unknown client',
      unknownOperator: 'Unknown operator',
      noReason: 'No reason provided',
    },
  },
  transfers: {
    uz: {
      headTitle: "O'tkazmalar",
      eyebrow: 'Balance transfer',
      title: "O'tkazmalar",
      subtitle: "Klientlar orasidagi o'tkazmalarni tez ko'rish va tekshirish uchun yengil ro'yxat.",
      updatedAt: 'Yangilanish',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      searchPlaceholder: 'From, to, operator yoki ID bo‘yicha qidiring...',
      totalRows: 'Topildi',
      pageAmount: 'Sahifa summasi',
      uniqueClients: 'Klientlar',
      count: 'Soni',
      noData: "O'tkazma topilmadi.",
      date: 'Sana',
      from: 'Kimdan',
      to: 'Kimga',
      amount: 'Summa',
      operator: 'Operator',
      shift: 'Smena',
      page: 'Sahifa',
      prev: 'Oldingi',
      next: 'Keyingi',
      unknownClient: 'Noma’lum klient',
      unknownOperator: 'Noma’lum operator',
    },
    ru: {
      headTitle: 'Переводы',
      eyebrow: 'Balance transfer',
      title: 'Переводы',
      subtitle: 'Легкий список для проверки переводов между клиентами.',
      updatedAt: 'Обновлено',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      searchPlaceholder: 'Поиск по отправителю, получателю, оператору или ID...',
      totalRows: 'Найдено',
      pageAmount: 'Сумма страницы',
      uniqueClients: 'Клиенты',
      count: 'Кол-во',
      noData: 'Переводы не найдены.',
      date: 'Дата',
      from: 'От кого',
      to: 'Кому',
      amount: 'Сумма',
      operator: 'Оператор',
      shift: 'Смена',
      page: 'Страница',
      prev: 'Назад',
      next: 'Далее',
      unknownClient: 'Неизвестный клиент',
      unknownOperator: 'Неизвестный оператор',
    },
    en: {
      headTitle: 'Transfers',
      eyebrow: 'Balance transfer',
      title: 'Transfers',
      subtitle: 'A lightweight list for quick review of client-to-client transfers.',
      updatedAt: 'Updated',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      searchPlaceholder: 'Search by sender, receiver, operator, or ID...',
      totalRows: 'Found',
      pageAmount: 'Page amount',
      uniqueClients: 'Clients',
      count: 'Count',
      noData: 'No transfers found.',
      date: 'Date',
      from: 'From',
      to: 'To',
      amount: 'Amount',
      operator: 'Operator',
      shift: 'Shift',
      page: 'Page',
      prev: 'Prev',
      next: 'Next',
      unknownClient: 'Unknown client',
      unknownOperator: 'Unknown operator',
    },
  },
  sessions: {
    uz: {
      headTitle: 'Sessiyalar',
      eyebrow: 'Live usage',
      title: 'Sessiyalar',
      subtitle: "Qaysi PC bandligi, qaysi sessiya uzoq davom etayotgani va qayerda operator aralashuvi kerakligi birdan ko'rinadi.",
      updatedAt: 'Oxirgi yangilanish',
      zone: 'Zona',
      allZones: 'Barchasi',
      searchPlaceholder: 'PC, mijoz yoki zona...',
      sortDuration: 'Eng uzun',
      sortPc: 'PC',
      sortClient: 'Mijoz',
      sortStarted: 'Boshlangan vaqt',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      activeSessions: 'Aktiv sessiyalar',
      zonesCount: 'ta zona',
      averageDuration: "O'rtacha davomiylik",
      longestLabel: 'Eng uzun {value} min',
      busiestZone: 'Eng band zona',
      longSessionsTitle: 'Uzoq davom etayotgan sessiyalar',
      longSessionsSubtitle: "Ko'p vaqt ishlayotgan sessiyalarni tez ko'rish uchun.",
      noLongSessions: 'Hozircha uzoq sessiya topilmadi.',
      listTitle: "Jonli sessiyalar ro'yxati",
      listSubtitle: "Tezkor to'xtatish va operator ko'rishi uchun soddalashtirilgan jadval.",
      pc: 'PC',
      client: 'Mijoz',
      zoneLabel: 'Zona',
      startedAt: 'Boshlangan',
      duration: 'Davomiylik',
      stop: 'Tugatish',
      noSessions: 'Aktiv sessiya topilmadi.',
      noZone: 'Zonasiz',
      noOperator: "Operator ko'rsatilmagan",
      noIp: "IP yo'q",
      noTariff: "Tarif ko'rsatilmagan",
      unitSessions: 'sessiya',
      confirmTitle: 'Tasdiqlash',
      confirmYes: 'Ha',
      confirmNo: "Yo'q",
      stopConfirm: '{pc} sessiyasi tugatilsinmi?',
      stopped: 'Sessiya tugatildi.',
    },
    ru: {
      headTitle: 'Сессии',
      eyebrow: 'Живая загрузка',
      title: 'Сессии',
      subtitle: 'Сразу видно, какой ПК занят, какие сессии идут слишком долго и где нужен оператор.',
      updatedAt: 'Последнее обновление',
      zone: 'Зона',
      allZones: 'Все',
      searchPlaceholder: 'ПК, клиент или зона...',
      sortDuration: 'Самые долгие',
      sortPc: 'ПК',
      sortClient: 'Клиент',
      sortStarted: 'Время старта',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      activeSessions: 'Активные сессии',
      zonesCount: 'зон',
      averageDuration: 'Средняя длительность',
      longestLabel: 'Максимум {value} мин',
      busiestZone: 'Самая загруженная зона',
      longSessionsTitle: 'Долгие сессии',
      longSessionsSubtitle: 'Чтобы быстро видеть самые длительные активные сессии.',
      noLongSessions: 'Долгих сессий пока нет.',
      listTitle: 'Список живых сессий',
      listSubtitle: 'Упрощенная таблица для быстрого завершения и контроля оператором.',
      pc: 'ПК',
      client: 'Клиент',
      zoneLabel: 'Зона',
      startedAt: 'Старт',
      duration: 'Длительность',
      stop: 'Завершить',
      noSessions: 'Активные сессии не найдены.',
      noZone: 'Без зоны',
      noOperator: 'Оператор не указан',
      noIp: 'Нет IP',
      noTariff: 'Тариф не указан',
      unitSessions: 'сессий',
      confirmTitle: 'Подтверждение',
      confirmYes: 'Да',
      confirmNo: 'Нет',
      stopConfirm: 'Завершить сессию {pc}?',
      stopped: 'Сессия завершена.',
    },
    en: {
      headTitle: 'Sessions',
      eyebrow: 'Live usage',
      title: 'Sessions',
      subtitle: 'See which PCs are busy, which sessions run too long, and where operator action is needed.',
      updatedAt: 'Last update',
      zone: 'Zone',
      allZones: 'All',
      searchPlaceholder: 'PC, client, or zone...',
      sortDuration: 'Longest',
      sortPc: 'PC',
      sortClient: 'Client',
      sortStarted: 'Started at',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      activeSessions: 'Active sessions',
      zonesCount: 'zones',
      averageDuration: 'Average duration',
      longestLabel: 'Longest {value} min',
      busiestZone: 'Busiest zone',
      longSessionsTitle: 'Long-running sessions',
      longSessionsSubtitle: 'Quickly spot sessions that have been running for a long time.',
      noLongSessions: 'No long-running sessions yet.',
      listTitle: 'Live sessions list',
      listSubtitle: 'A simplified table for quick stop actions and operator control.',
      pc: 'PC',
      client: 'Client',
      zoneLabel: 'Zone',
      startedAt: 'Started',
      duration: 'Duration',
      stop: 'Stop',
      noSessions: 'No active sessions found.',
      noZone: 'No zone',
      noOperator: 'Operator not set',
      noIp: 'No IP',
      noTariff: 'Tariff not set',
      unitSessions: 'sessions',
      confirmTitle: 'Confirm',
      confirmYes: 'Yes',
      confirmNo: 'No',
      stopConfirm: 'Stop session for {pc}?',
      stopped: 'Session stopped.',
    },
  },
  shift: {
    uz: {
      headTitle: 'Smena',
      eyebrow: 'Cash desk',
      title: 'Smena',
      subtitle: "Kassa oqimi, xarajatlar va yopishdagi farqni operator bir qarashda tushunadi.",
      closed: 'Shift yopiq',
      syncedAt: 'Sinxron',
      notSynced: 'Sinxronlanmagan',
      autoRefresh: 'Auto 30s',
      refresh: 'Yangilash',
      openShift: 'Smena ochish',
      closeShift: 'Smenani yopish',
      revenue: 'Tushum',
      expectedCash: 'Kutilgan naqd',
      expenses: 'Xarajatlar',
      discipline: 'Intizom',
      opening: 'Opening',
      returns: 'Return',
      share: 'ulush',
      pageError: "Shift ma'lumotlari yuklanmadi.",
      cashflowTitle: 'Cashflow',
      cashflowSubtitle: "Formula bo'yicha kutilgan kassa holati.",
      openingCash: "Boshlang'ich naqd",
      cashIncome: 'Naqd tushum',
      expectedTotal: 'Kutilgan naqd',
      handover: 'Handover',
      assistantTitle: 'Operator yordamchisi',
      assistantSubtitle: "Current shift bo'yicha tavsiyalar.",
      operator: 'Operator',
      sales: 'Sotuv',
      net: 'Sof',
      noOperatorData: "Operator kesimi uchun ma'lumot yo'q.",
      expensesTitle: 'Xarajatlar',
      expensesSubtitle: "Ochiq smenada xarajat qo'shish va boshqarish.",
      addExpense: "Xarajat qo'shish",
      other: 'Boshqa',
      remove: "O'chirish",
      noExpenses: "Hozircha xarajat yo'q.",
      returnsTitle: 'Qaytarishlar',
      returnsSubtitle: "Naqd qaytarishlar yopishdan oldin ko'rib chiqiladi.",
      noReturns: "Qaytarish yo'q.",
      openShiftTitle: 'Smenani ochish',
      cancel: 'Bekor',
      open: 'Ochish',
      closeShiftTitle: 'Smenani yopish',
      byFormula: "Formula bo'yicha",
      actualCash: 'Amaldagi naqd',
      diff: 'Farq',
      diffMatch: 'Mos',
      diffExtra: 'Ortiqcha',
      diffShortage: 'Kamomad',
      cashCounted: 'Naqd sanaldi',
      expensesChecked: 'Xarajatlar tekshirildi',
      returnsChecked: 'Qaytarishlar tekshirildi',
      closeConfirm: 'Tasdiqlab yopish',
      newExpenseTitle: 'Yangi xarajat',
      amount: 'Summa',
      name: 'Nomi',
      category: 'Kategoriya',
      note: 'Izoh',
      save: 'Saqlash',
      shiftOpenError: 'Smenani ochishda xato.',
      shiftCloseError: 'Smenani yopishda xato.',
      expenseCreateError: "Xarajat qo'shib bo'lmadi.",
      removeExpenseConfirm: "{title} o'chirilsinmi?",
      confirmTitle: 'Tasdiqlash',
      confirmYes: 'Ha',
      confirmNo: "Yo'q",
      expenseRemoved: "Xarajat o'chirildi.",
      disciplinePending: 'Smena ochilganda hisoblanadi',
      disciplineGood: 'Nazorat yaxshi',
      disciplineMedium: 'Bir oz tekshiruv kerak',
      disciplineBad: 'Owner nazorati kerak',
      closedHints: [
        'Smena yopiq: avval opening naqd bilan yangi smena oching.',
        'Opening qiymatni real kassa bilan teng kiriting.',
        "Yopishda checklistni to'liq belgilang.",
      ],
      opsRecorded: 'Jami {value} ta operatsiya qayd etilgan.',
      expenseHigh: "Xarajat ulushi yuqori, cheklarni qayta tekshiring.",
      expenseNormal: 'Xarajat ulushi meyorda.',
      returnsPresent: 'Naqd qaytarish mavjud: {value}.',
      returnsAbsent: "Naqd qaytarish yo'q.",
      topCategory: 'Eng katta kategoriya: {value}.',
      noHandover: "Oldingi smenadan handover ma'lumoti topilmadi.",
      carryFull: "Kamomad openingga to'liq ko'chgan.",
      carryPartial: "Kamomad qisman openingga ko'chgan.",
      carryNone: "Kamomad openingga o'tmagan, owner bilan tekshiring.",
      noShortage: "Oldingi smenada kamomad qayd etilmagan.",
    },
    ru: {
      headTitle: 'Смена',
      eyebrow: 'Касса',
      title: 'Смена',
      subtitle: 'Оператор сразу видит денежный поток, расходы и разницу при закрытии смены.',
      closed: 'Смена закрыта',
      syncedAt: 'Синхронизировано',
      notSynced: 'Не синхронизировано',
      autoRefresh: 'Авто 30с',
      refresh: 'Обновить',
      openShift: 'Открыть смену',
      closeShift: 'Закрыть смену',
      revenue: 'Выручка',
      expectedCash: 'Ожидаемая наличность',
      expenses: 'Расходы',
      discipline: 'Дисциплина',
      opening: 'Открытие',
      returns: 'Возвраты',
      share: 'доля',
      pageError: 'Не удалось загрузить данные смены.',
      cashflowTitle: 'Денежный поток',
      cashflowSubtitle: 'Ожидаемое состояние кассы по формуле.',
      openingCash: 'Стартовая наличность',
      cashIncome: 'Наличная выручка',
      expectedTotal: 'Ожидаемая наличность',
      handover: 'Передача',
      assistantTitle: 'Помощник оператора',
      assistantSubtitle: 'Подсказки по текущей смене.',
      operator: 'Оператор',
      sales: 'Продажи',
      net: 'Чистыми',
      noOperatorData: 'Нет данных по операторам.',
      expensesTitle: 'Расходы',
      expensesSubtitle: 'Добавление и контроль расходов в открытой смене.',
      addExpense: 'Добавить расход',
      other: 'Другое',
      remove: 'Удалить',
      noExpenses: 'Расходов пока нет.',
      returnsTitle: 'Возвраты',
      returnsSubtitle: 'Наличные возвраты проверяются перед закрытием.',
      noReturns: 'Возвратов нет.',
      openShiftTitle: 'Открытие смены',
      cancel: 'Отмена',
      open: 'Открыть',
      closeShiftTitle: 'Закрытие смены',
      byFormula: 'По формуле',
      actualCash: 'Фактическая наличность',
      diff: 'Разница',
      diffMatch: 'Совпадает',
      diffExtra: 'Излишек',
      diffShortage: 'Недостача',
      cashCounted: 'Наличные пересчитаны',
      expensesChecked: 'Расходы проверены',
      returnsChecked: 'Возвраты проверены',
      closeConfirm: 'Подтвердить закрытие',
      newExpenseTitle: 'Новый расход',
      amount: 'Сумма',
      name: 'Название',
      category: 'Категория',
      note: 'Комментарий',
      save: 'Сохранить',
      shiftOpenError: 'Ошибка при открытии смены.',
      shiftCloseError: 'Ошибка при закрытии смены.',
      expenseCreateError: 'Не удалось добавить расход.',
      removeExpenseConfirm: 'Удалить "{title}"?',
      confirmTitle: 'Подтверждение',
      confirmYes: 'Да',
      confirmNo: 'Нет',
      expenseRemoved: 'Расход удален.',
      disciplinePending: 'Рассчитывается после открытия смены',
      disciplineGood: 'Контроль хороший',
      disciplineMedium: 'Нужна дополнительная проверка',
      disciplineBad: 'Нужен контроль владельца',
      closedHints: [
        'Смена закрыта: сначала откройте новую смену со стартовой наличностью.',
        'Стартовая сумма должна совпадать с реальной кассой.',
        'При закрытии полностью пройдите чеклист.',
      ],
      opsRecorded: 'Зафиксировано операций: {value}.',
      expenseHigh: 'Доля расходов высокая, перепроверьте чеки.',
      expenseNormal: 'Доля расходов в норме.',
      returnsPresent: 'Есть наличные возвраты: {value}.',
      returnsAbsent: 'Наличных возвратов нет.',
      topCategory: 'Крупнейшая категория: {value}.',
      noHandover: 'Нет данных о передаче с прошлой смены.',
      carryFull: 'Недостача полностью перенесена в opening.',
      carryPartial: 'Недостача частично перенесена в opening.',
      carryNone: 'Недостача не перенесена, проверьте с owner.',
      noShortage: 'В прошлой смене недостача не зафиксирована.',
    },
    en: {
      headTitle: 'Shift',
      eyebrow: 'Cash desk',
      title: 'Shift',
      subtitle: 'The operator can immediately see the cashflow, expenses, and close-out difference.',
      closed: 'Shift closed',
      syncedAt: 'Synced',
      notSynced: 'Not synced',
      autoRefresh: 'Auto 30s',
      refresh: 'Refresh',
      openShift: 'Open shift',
      closeShift: 'Close shift',
      revenue: 'Revenue',
      expectedCash: 'Expected cash',
      expenses: 'Expenses',
      discipline: 'Discipline',
      opening: 'Opening',
      returns: 'Returns',
      share: 'share',
      pageError: 'Shift data could not be loaded.',
      cashflowTitle: 'Cashflow',
      cashflowSubtitle: 'Expected cash position based on the formula.',
      openingCash: 'Opening cash',
      cashIncome: 'Cash revenue',
      expectedTotal: 'Expected cash',
      handover: 'Handover',
      assistantTitle: 'Operator assistant',
      assistantSubtitle: 'Current shift recommendations.',
      operator: 'Operator',
      sales: 'Sales',
      net: 'Net',
      noOperatorData: 'No operator breakdown data.',
      expensesTitle: 'Expenses',
      expensesSubtitle: 'Add and control expenses during an open shift.',
      addExpense: 'Add expense',
      other: 'Other',
      remove: 'Remove',
      noExpenses: 'No expenses yet.',
      returnsTitle: 'Returns',
      returnsSubtitle: 'Cash returns should be reviewed before closing.',
      noReturns: 'No returns.',
      openShiftTitle: 'Open shift',
      cancel: 'Cancel',
      open: 'Open',
      closeShiftTitle: 'Close shift',
      byFormula: 'By formula',
      actualCash: 'Actual cash',
      diff: 'Difference',
      diffMatch: 'Match',
      diffExtra: 'Surplus',
      diffShortage: 'Shortage',
      cashCounted: 'Cash counted',
      expensesChecked: 'Expenses checked',
      returnsChecked: 'Returns checked',
      closeConfirm: 'Confirm close',
      newExpenseTitle: 'New expense',
      amount: 'Amount',
      name: 'Name',
      category: 'Category',
      note: 'Note',
      save: 'Save',
      shiftOpenError: 'Shift could not be opened.',
      shiftCloseError: 'Shift could not be closed.',
      expenseCreateError: 'Expense could not be added.',
      removeExpenseConfirm: 'Remove "{title}"?',
      confirmTitle: 'Confirm',
      confirmYes: 'Yes',
      confirmNo: 'No',
      expenseRemoved: 'Expense removed.',
      disciplinePending: 'Calculated after shift open',
      disciplineGood: 'Control is strong',
      disciplineMedium: 'Needs a quick review',
      disciplineBad: 'Owner review is needed',
      closedHints: [
        'Shift is closed: open a new shift with the opening cash first.',
        'Enter an opening amount that matches the real cash desk.',
        'Complete the close checklist before closing.',
      ],
      opsRecorded: '{value} operations have been recorded.',
      expenseHigh: 'Expense share is high. Re-check the receipts.',
      expenseNormal: 'Expense share is within the norm.',
      returnsPresent: 'Cash returns present: {value}.',
      returnsAbsent: 'No cash returns.',
      topCategory: 'Largest category: {value}.',
      noHandover: 'No handover data from the previous shift.',
      carryFull: 'The shortage was fully carried into opening.',
      carryPartial: 'The shortage was partially carried into opening.',
      carryNone: 'The shortage was not carried. Check with the owner.',
      noShortage: 'No shortage was recorded in the previous shift.',
    },
  },
  reports: {
    uz: {
      headTitle: 'Hisobotlar',
      eyebrow: 'Owner analytics',
      title: 'Hisobotlar',
      subtitle: "Tushum, yuklama, autopilot tavsiyalari va exchange holatini ortiqcha shovqinsiz ko'rish mumkin.",
      updatedAt: 'Yangilanish',
      refresh: 'Yangilash',
      refreshing: 'Yuklanmoqda...',
      tabOverview: 'Overview',
      tabAutopilot: 'Autopilot',
      tabExchange: 'Exchange',
      netRevenue: 'Sof tushum',
      sessions: 'Sessiyalar',
      clients: 'Mijozlar',
      risk: 'Risk',
      growthTitle: "O'sish indikatorlari",
      growthSubtitle: "Oldingi davr bilan taqqoslash.",
      noGrowth: "Taqqoslash ma'lumoti topilmadi.",
      mixTitle: "To'lov aralashmasi",
      mixSubtitle: "Qaysi kanal ko'proq ishlaganini ko'rsatadi.",
      cash: 'Naqd',
      card: 'Karta',
      balance: 'Balans',
      topClientsTitle: 'Top mijozlar',
      topClientsSubtitle: "Sarf bo'yicha eng faol foydalanuvchilar.",
      topClientsEmpty: "Top mijozlar ma'lumoti yo'q.",
      zonesTitle: 'Zona kesimi',
      zonesSubtitle: "Sessiya va tushum bo'yicha bo'lingan ko'rinish.",
      zonesEmpty: "Zona ma'lumoti yo'q.",
      dailyTitle: 'Kunlik trend',
      dailySubtitle: "Oxirgi kunlar bo'yicha gross va net oqimi.",
      dailyEmpty: "Tanlangan davr uchun kunlik ma'lumot topilmadi.",
      autopilotSummaryTitle: 'Autopilot summary',
      autopilotSummarySubtitle: 'Backend tavsiyalari va kutilayotgan uplift.',
      balanced: 'Balanced',
      growth: 'Growth',
      aggressive: 'Aggressive',
      recalc: 'Qayta hisoblash',
      confidence: 'Confidence',
      zoneUpdate: 'Zone update',
      promo: 'Promo',
      monthlyUplift: 'Monthly uplift',
      promoFallback: "Promo tavsiya yo'q",
      demandTitle: 'Demand signal',
      demandSubtitle: "Peak va low hour bo'yicha tavsiyalar.",
      peakHour: 'Peak hour',
      lowHour: 'Low hour',
      peakEmpty: "Peak ma'lumot yo'q.",
      lowEmpty: "Low ma'lumot yo'q.",
      zonePriceTitle: 'Zone price updates',
      zonePriceSubtitle: "Autopilot tavsiya qilayotgan o'zgarishlar.",
      zonePriceEmpty: "Price update tavsiyasi topilmadi.",
      exchangeSnapshotTitle: 'Exchange snapshot',
      exchangeSnapshotSubtitle: "Tarmoq bo'yicha yuklama va overflow bosimi.",
      clubLoad: 'Club load',
      readyPartners: 'Ready partners',
      crossClub: 'Cross-club',
      recoveredMonthly: 'Recovered monthly',
      exchangeConfigTitle: 'Exchange config',
      exchangeConfigSubtitle: 'Overflow va referral qoidalari.',
      enabled: 'Enabled',
      overflowEnabled: 'Overflow enabled',
      radiusKm: 'Radius km',
      minFreePcs: 'Min free PCs',
      referralBonus: 'Referral bonus',
      auctionFloor: 'Auction floor',
      on: 'On',
      off: 'Off',
      saveConfig: 'Config saqlash',
      topPartnersTitle: 'Top partners',
      topPartnersSubtitle: "Qabul qila oladigan yaqin hamkorlar.",
      topPartnersEmpty: 'Mos partner topilmadi.',
      requestError: "So'rov bajarilmadi.",
      configSaved: 'Exchange config saqlandi.',
      unitZones: 'ta zona',
      unitPassports: 'passportlar',
      unitHours: 'soat',
      unitSessions: 'sessiya',
      active: 'aktiv',
      freePc: 'free PC',
      growthLabels: {
        net_sales: 'Sof tushum',
        gross_sales: 'Jami savdo',
        sessions_count: 'Sessiyalar',
        avg_session_minutes: "O'rtacha sessiya",
        utilization_pct: 'Bandlik',
        cash_net: 'Naqd net',
        card_net: 'Karta net',
        clients_in_period: 'Davrdagi mijozlar',
      },
    },
    ru: {
      headTitle: 'Отчеты',
      eyebrow: 'Аналитика owner',
      title: 'Отчеты',
      subtitle: 'Выручка, загрузка, рекомендации autopilot и состояние exchange показаны без лишнего шума.',
      updatedAt: 'Обновление',
      refresh: 'Обновить',
      refreshing: 'Загрузка...',
      tabOverview: 'Обзор',
      tabAutopilot: 'Autopilot',
      tabExchange: 'Exchange',
      netRevenue: 'Чистая выручка',
      sessions: 'Сессии',
      clients: 'Клиенты',
      risk: 'Риск',
      growthTitle: 'Индикаторы роста',
      growthSubtitle: 'Сравнение с предыдущим периодом.',
      noGrowth: 'Данные сравнения не найдены.',
      mixTitle: 'Структура оплат',
      mixSubtitle: 'Показывает, какой канал работал лучше.',
      cash: 'Наличные',
      card: 'Карта',
      balance: 'Баланс',
      topClientsTitle: 'Топ клиентов',
      topClientsSubtitle: 'Самые активные пользователи по расходам.',
      topClientsEmpty: 'Нет данных по топ клиентам.',
      zonesTitle: 'Разрез по зонам',
      zonesSubtitle: 'Сессии и выручка по зонам.',
      zonesEmpty: 'Нет данных по зонам.',
      dailyTitle: 'Дневной тренд',
      dailySubtitle: 'Поток gross и net по последним дням.',
      dailyEmpty: 'Нет дневных данных за выбранный период.',
      autopilotSummaryTitle: 'Сводка autopilot',
      autopilotSummarySubtitle: 'Рекомендации backend и ожидаемый uplift.',
      balanced: 'Balanced',
      growth: 'Growth',
      aggressive: 'Aggressive',
      recalc: 'Пересчитать',
      confidence: 'Confidence',
      zoneUpdate: 'Zone update',
      promo: 'Promo',
      monthlyUplift: 'Monthly uplift',
      promoFallback: 'Нет рекомендации по акции',
      demandTitle: 'Сигнал спроса',
      demandSubtitle: 'Рекомендации по peak и low hour.',
      peakHour: 'Peak hour',
      lowHour: 'Low hour',
      peakEmpty: 'Нет данных по peak.',
      lowEmpty: 'Нет данных по low.',
      zonePriceTitle: 'Обновления цен зон',
      zonePriceSubtitle: 'Изменения, которые предлагает autopilot.',
      zonePriceEmpty: 'Нет ценовых рекомендаций.',
      exchangeSnapshotTitle: 'Снимок exchange',
      exchangeSnapshotSubtitle: 'Загрузка сети и overflow pressure.',
      clubLoad: 'Club load',
      readyPartners: 'Ready partners',
      crossClub: 'Cross-club',
      recoveredMonthly: 'Recovered monthly',
      exchangeConfigTitle: 'Настройки exchange',
      exchangeConfigSubtitle: 'Правила overflow и referral.',
      enabled: 'Enabled',
      overflowEnabled: 'Overflow enabled',
      radiusKm: 'Радиус км',
      minFreePcs: 'Мин. свободных ПК',
      referralBonus: 'Referral bonus',
      auctionFloor: 'Auction floor',
      on: 'On',
      off: 'Off',
      saveConfig: 'Сохранить конфиг',
      topPartnersTitle: 'Топ партнеров',
      topPartnersSubtitle: 'Ближайшие партнеры, которые могут принять поток.',
      topPartnersEmpty: 'Подходящие партнеры не найдены.',
      requestError: 'Запрос не выполнен.',
      configSaved: 'Конфиг exchange сохранен.',
      unitZones: 'зон',
      unitPassports: 'паспортов',
      unitHours: 'час',
      unitSessions: 'сессий',
      active: 'активных',
      freePc: 'свободных ПК',
      growthLabels: {
        net_sales: 'Чистая выручка',
        gross_sales: 'Валовая выручка',
        sessions_count: 'Сессии',
        avg_session_minutes: 'Средняя сессия',
        utilization_pct: 'Загрузка',
        cash_net: 'Чистые наличные',
        card_net: 'Чистая карта',
        clients_in_period: 'Клиенты за период',
      },
    },
    en: {
      headTitle: 'Reports',
      eyebrow: 'Owner analytics',
      title: 'Reports',
      subtitle: 'Revenue, load, autopilot recommendations, and exchange state are presented without extra noise.',
      updatedAt: 'Updated',
      refresh: 'Refresh',
      refreshing: 'Loading...',
      tabOverview: 'Overview',
      tabAutopilot: 'Autopilot',
      tabExchange: 'Exchange',
      netRevenue: 'Net revenue',
      sessions: 'Sessions',
      clients: 'Clients',
      risk: 'Risk',
      growthTitle: 'Growth indicators',
      growthSubtitle: 'Comparison with the previous period.',
      noGrowth: 'No comparison data found.',
      mixTitle: 'Payment mix',
      mixSubtitle: 'Shows which channel performed better.',
      cash: 'Cash',
      card: 'Card',
      balance: 'Balance',
      topClientsTitle: 'Top clients',
      topClientsSubtitle: 'Most active users by spend.',
      topClientsEmpty: 'No top client data.',
      zonesTitle: 'Zone breakdown',
      zonesSubtitle: 'Sessions and revenue grouped by zone.',
      zonesEmpty: 'No zone data.',
      dailyTitle: 'Daily trend',
      dailySubtitle: 'Gross and net flow over recent days.',
      dailyEmpty: 'No daily data for the selected period.',
      autopilotSummaryTitle: 'Autopilot summary',
      autopilotSummarySubtitle: 'Backend recommendations and expected uplift.',
      balanced: 'Balanced',
      growth: 'Growth',
      aggressive: 'Aggressive',
      recalc: 'Recalculate',
      confidence: 'Confidence',
      zoneUpdate: 'Zone update',
      promo: 'Promo',
      monthlyUplift: 'Monthly uplift',
      promoFallback: 'No promo recommendation',
      demandTitle: 'Demand signal',
      demandSubtitle: 'Recommendations for peak and low hours.',
      peakHour: 'Peak hour',
      lowHour: 'Low hour',
      peakEmpty: 'No peak-hour data.',
      lowEmpty: 'No low-hour data.',
      zonePriceTitle: 'Zone price updates',
      zonePriceSubtitle: 'Changes suggested by autopilot.',
      zonePriceEmpty: 'No price update suggestions found.',
      exchangeSnapshotTitle: 'Exchange snapshot',
      exchangeSnapshotSubtitle: 'Network load and overflow pressure.',
      clubLoad: 'Club load',
      readyPartners: 'Ready partners',
      crossClub: 'Cross-club',
      recoveredMonthly: 'Recovered monthly',
      exchangeConfigTitle: 'Exchange config',
      exchangeConfigSubtitle: 'Overflow and referral rules.',
      enabled: 'Enabled',
      overflowEnabled: 'Overflow enabled',
      radiusKm: 'Radius km',
      minFreePcs: 'Min free PCs',
      referralBonus: 'Referral bonus',
      auctionFloor: 'Auction floor',
      on: 'On',
      off: 'Off',
      saveConfig: 'Save config',
      topPartnersTitle: 'Top partners',
      topPartnersSubtitle: 'Nearby partners that can accept overflow.',
      topPartnersEmpty: 'No matching partners found.',
      requestError: 'Request failed.',
      configSaved: 'Exchange config saved.',
      unitZones: 'zones',
      unitPassports: 'passports',
      unitHours: 'hours',
      unitSessions: 'sessions',
      active: 'active',
      freePc: 'free PCs',
      growthLabels: {
        net_sales: 'Net revenue',
        gross_sales: 'Gross sales',
        sessions_count: 'Sessions',
        avg_session_minutes: 'Average session',
        utilization_pct: 'Utilization',
        cash_net: 'Cash net',
        card_net: 'Card net',
        clients_in_period: 'Clients in period',
      },
    },
  },
} as const
